/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.DbDao;
import Classes.ProcedimentosAuxiliares;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carla
 * @Coauthor Peter
 */
public class Chamado extends javax.swing.JFrame {

    /**
     * Creates new form Chamado
     */
    public Chamado() {
        initComponents();
    }
    DbDao Dao = new DbDao();
    ProcedimentosAuxiliares Procedimentos = new ProcedimentosAuxiliares();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        inpNomeCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jDefeito = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEquipamentos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jGerar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cliente"));

        inpNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inpNomeClienteKeyReleased(evt);
            }
        });

        tbClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(inpNomeCliente))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(inpNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamentos"));

        jDefeito.setColumns(20);
        jDefeito.setRows(5);
        jScrollPane5.setViewportView(jDefeito);

        tbEquipamentos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbEquipamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Tipo", "Marca", "Serial"
            }
        ));
        jScrollPane2.setViewportView(tbEquipamentos);

        jLabel2.setText("Defeito Relatado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jGerar.setText("Gerar OS");
        jGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGerarActionPerformed(evt);
            }
        });

        jButton4.setText("Voltar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Abertura de OS");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jGerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGerar)
                    .addComponent(jButton4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerarActionPerformed
        // TODO add your handling code here:

        int LinhaCliente = tbClientes.getSelectedRow();
        int CodCliente = Integer.parseInt(tbClientes.getValueAt(LinhaCliente, 0).toString());
        
        int LinhaEquipamentos = tbEquipamentos.getSelectedRow();
        int CodEquipamento = Integer.parseInt(tbEquipamentos.getValueAt(LinhaEquipamentos, 0).toString());
        
        int Status = 1;
        String DatAbertura = Procedimentos.DataAtual();
        String Defeito = jDefeito.getText();

        try {
            Dao.CreateChamados(CodCliente, CodEquipamento, Status, DatAbertura, Defeito);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro");
        }


    }//GEN-LAST:event_jGerarActionPerformed

    private void inpNomeClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpNomeClienteKeyReleased
        // TODO add your handling code here:
        PesquisaCliente();
        PesquisaEquipamentos();
    }//GEN-LAST:event_inpNomeClienteKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        tbClientes.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbClientes.getColumnModel().getColumn(1).setPreferredWidth(450);
    }//GEN-LAST:event_formWindowActivated

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        // TODO add your handling code here:
        PesquisaEquipamentos();
    }//GEN-LAST:event_tbClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inpNomeCliente;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextArea jDefeito;
    private javax.swing.JButton jGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTable tbEquipamentos;
    // End of variables declaration//GEN-END:variables

    private void PesquisaCliente() {
        Dao.conectar();
        Connection con = Dao.getConn();
        try {
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbchamados", "root", "");
            String sql = "select * from Clientes";
            if (!inpNomeCliente.getText().equals("")) {
                sql = sql + " where Nome LIKE ? ";
            }
            PreparedStatement stmt = con.prepareStatement(sql);
            if (!inpNomeCliente.getText().equals("")) {
                stmt.setString(1, inpNomeCliente.getText() + "%");
            }

            ResultSet rs = stmt.executeQuery();
//            ResultSet rs = Buscas.PesquisaCliente(jTextNome.getText());
            DefaultTableModel TabClientes = (DefaultTableModel) tbClientes.getModel();
            TabClientes.setNumRows(0);
            while (rs.next()) {
                String[] linha = {
                    rs.getString("ID"),
                    rs.getString("Nome"),
                    rs.getString("DataNasc"),
                    rs.getString("Cel"),
                    rs.getString("Endereco"),
                    rs.getString("Genero")
                };
                TabClientes.addRow(linha);
//              Seleciona a primara linha da tabela
                tbClientes.setRowSelectionInterval(0, 0);
            }
//            stmt.close();
//            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        Dao.Desconectar();
    }

    private void PesquisaEquipamentos() {
        Dao.conectar();
        Connection con = Dao.getConn();
        try {

            String sql = "select * from equipamentos where ClienteID = " + SelecionaCodCliente();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet ResultadoEquipamentos = stmt.executeQuery();

            DefaultTableModel TabelaEquipamentos = (DefaultTableModel) tbEquipamentos.getModel();
            TabelaEquipamentos.setNumRows(0);
            while (ResultadoEquipamentos.next()) {
                String[] linha = {
                    ResultadoEquipamentos.getString("ID"),
                    ResultadoEquipamentos.getString("TipoEquip"),
                    ResultadoEquipamentos.getString("Marca"),
                    ResultadoEquipamentos.getString("Serial")
                };
                TabelaEquipamentos.addRow(linha);
            }
            stmt.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private String SelecionaCodCliente() {
        int LinhaTabelaCliente = tbClientes.getSelectedRow();
        String CodCli = tbClientes.getValueAt(LinhaTabelaCliente, 0).toString();
        return CodCli;
    }

    

}
