/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Classes.DbDao;

/**
 *
 * @author peter - Carla - Victor
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pnCadUsers = new javax.swing.JPanel();
        btCadUsuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnCadClientes = new javax.swing.JPanel();
        btCadCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pnCadAtendimentos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btCadAtendimentos = new javax.swing.JButton();
        pnCadOS = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btCadOS = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        MenuCadastros = new javax.swing.JMenu();
        imUsuarios = new javax.swing.JMenuItem();
        imClientes = new javax.swing.JMenuItem();
        MenuChamados = new javax.swing.JMenu();
        imChamados = new javax.swing.JMenuItem();
        imAtendimentos = new javax.swing.JMenuItem();
        imSair = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        imSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Chamados - Usuário: Nivel:");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Cadastros ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        pnCadUsers.setBackground(new java.awt.Color(0, 153, 255));

        btCadUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adm2.png"))); // NOI18N
        btCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadUsuariosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Usuários");

        javax.swing.GroupLayout pnCadUsersLayout = new javax.swing.GroupLayout(pnCadUsers);
        pnCadUsers.setLayout(pnCadUsersLayout);
        pnCadUsersLayout.setHorizontalGroup(
            pnCadUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadUsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadUsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        pnCadUsersLayout.setVerticalGroup(
            pnCadUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadUsersLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnCadClientes.setBackground(new java.awt.Color(255, 255, 0));

        btCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AddUsuario2.png"))); // NOI18N
        btCadCliente.setMaximumSize(new java.awt.Dimension(222, 222));
        btCadCliente.setPreferredSize(new java.awt.Dimension(150, 150));
        btCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadClienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro de Clientes");

        javax.swing.GroupLayout pnCadClientesLayout = new javax.swing.GroupLayout(pnCadClientes);
        pnCadClientes.setLayout(pnCadClientesLayout);
        pnCadClientesLayout.setHorizontalGroup(
            pnCadClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadClientesLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnCadClientesLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        pnCadClientesLayout.setVerticalGroup(
            pnCadClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadClientesLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(pnCadUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(pnCadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnCadUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Ordem de Serviço ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        pnCadAtendimentos.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atender OS");

        btCadAtendimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AtendimentoOS3.png"))); // NOI18N
        btCadAtendimentos.setMaximumSize(new java.awt.Dimension(250, 250));
        btCadAtendimentos.setMinimumSize(new java.awt.Dimension(250, 250));
        btCadAtendimentos.setPreferredSize(new java.awt.Dimension(250, 250));
        btCadAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadAtendimentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadAtendimentosLayout = new javax.swing.GroupLayout(pnCadAtendimentos);
        pnCadAtendimentos.setLayout(pnCadAtendimentosLayout);
        pnCadAtendimentosLayout.setHorizontalGroup(
            pnCadAtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadAtendimentosLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btCadAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCadAtendimentosLayout.setVerticalGroup(
            pnCadAtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadAtendimentosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pnCadOS.setBackground(java.awt.Color.green);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Abrir Ordem e Serviço");

        btCadOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OS2.png"))); // NOI18N
        btCadOS.setMaximumSize(new java.awt.Dimension(250, 250));
        btCadOS.setMinimumSize(new java.awt.Dimension(250, 250));
        btCadOS.setPreferredSize(new java.awt.Dimension(250, 250));
        btCadOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadOSLayout = new javax.swing.GroupLayout(pnCadOS);
        pnCadOS.setLayout(pnCadOSLayout);
        pnCadOSLayout.setHorizontalGroup(
            pnCadOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadOSLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(btCadOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCadOSLayout.setVerticalGroup(
            pnCadOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadOSLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadOS, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(pnCadOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(pnCadAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnCadAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCadOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        menuSistema.setText("Sistema");

        MenuCadastros.setText("Cadastros");
        MenuCadastros.setEnabled(false);

        imUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, 0));
        imUsuarios.setText("Usuários do Sistema");
        imUsuarios.setEnabled(false);
        imUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imUsuariosActionPerformed(evt);
            }
        });
        MenuCadastros.add(imUsuarios);

        imClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        imClientes.setText("Clientes / Equipamentos");
        imClientes.setEnabled(false);
        imClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imClientesActionPerformed(evt);
            }
        });
        MenuCadastros.add(imClientes);

        menuSistema.add(MenuCadastros);

        MenuChamados.setText("Chamados");
        MenuChamados.setEnabled(false);

        imChamados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        imChamados.setText("Abrir Ordem de Serviços");
        imChamados.setEnabled(false);
        imChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imChamadosActionPerformed(evt);
            }
        });
        MenuChamados.add(imChamados);

        imAtendimentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        imAtendimentos.setText("Atender OS");
        imAtendimentos.setEnabled(false);
        imAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imAtendimentosActionPerformed(evt);
            }
        });
        MenuChamados.add(imAtendimentos);

        menuSistema.add(MenuChamados);

        imSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        imSair.setText("Sair");
        imSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imSairActionPerformed(evt);
            }
        });
        menuSistema.add(imSair);

        jMenuBar1.add(menuSistema);

        MenuAjuda.setText("Ajuda");

        imSobre.setText("Sobre o Sistema");
        MenuAjuda.add(imSobre);

        jMenuBar1.add(MenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imUsuariosActionPerformed
        CadUsuario CadastroUsuarios = new CadUsuario();
        CadastroUsuarios.setVisible(true);
    }//GEN-LAST:event_imUsuariosActionPerformed

    DbDao Dao = new DbDao();
//    Logar Login = new Logar(new javax.swing.JFrame(), true);
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String DadosLogados[] = new String[2];
        DadosLogados = Dao.DadosUsuarioLogado();
        String TituloTela = null;

        switch (DadosLogados[1]) {
            case "1":
                TituloTela = "Sistema de Chamados - Usuário: " + DadosLogados[0] + ". Nivel: ADMINISTRADOR ";
                
                MenuCadastros.setEnabled(true);
                imUsuarios.setEnabled(true);
                imClientes.setEnabled(true);

                MenuChamados.setEnabled(true);
                imChamados.setEnabled(true);
                imAtendimentos.setEnabled(true);
                
                btCadUsuarios.setEnabled(true);
                btCadCliente.setEnabled(true);
                btCadOS.setEnabled(true);
                btCadAtendimentos.setEnabled(true);
                
                break;
            case "2":
                TituloTela = "Sistema de Chamados - Usuário: " + DadosLogados[0] + ". Nivel: GERENTE ";
                
                MenuCadastros.setEnabled(true);
                imUsuarios.setEnabled(false);
                imClientes.setEnabled(true);

                MenuChamados.setEnabled(true);
                imChamados.setEnabled(true);
                imAtendimentos.setEnabled(true);
                
                btCadUsuarios.setEnabled(false);
                btCadCliente.setEnabled(true);
                btCadOS.setEnabled(true);
                btCadAtendimentos.setEnabled(true);
                
                break;
            case "3":
                TituloTela = "Sistema de Chamados - Usuário: " + DadosLogados[0] + ". Nivel: TÉCNICO ";
                
                MenuCadastros.setEnabled(false);
                imUsuarios.setEnabled(false);
                imClientes.setEnabled(false);

                MenuChamados.setEnabled(true);
                imChamados.setEnabled(true);
                imAtendimentos.setEnabled(true);
                
                btCadUsuarios.setEnabled(false);
                btCadCliente.setEnabled(false);
                btCadOS.setEnabled(true);
                btCadAtendimentos.setEnabled(true);
                
                break;
            default:
                break;
        }
        this.setTitle(TituloTela);
    }//GEN-LAST:event_formWindowOpened

    private void imClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imClientesActionPerformed
        CadCliente CadastroCliente = new CadCliente();
        CadastroCliente.setVisible(true);
    }//GEN-LAST:event_imClientesActionPerformed

    private void imSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imSairActionPerformed
        this.setVisible(false);
        Login Login = new Login();
        Login.setVisible(true);

    }//GEN-LAST:event_imSairActionPerformed

    private void imChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imChamadosActionPerformed
        // TODO add your handling code here:
        CadChamado chamados = new CadChamado();
        chamados.setVisible(true);

    }//GEN-LAST:event_imChamadosActionPerformed

    private void imAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imAtendimentosActionPerformed
        CadAtendimentos Atendimento = new CadAtendimentos();
        Atendimento.setVisible(true);
    }//GEN-LAST:event_imAtendimentosActionPerformed

    private void btCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadClienteActionPerformed
        new CadCliente().setVisible(true);//que quer abrir
    }//GEN-LAST:event_btCadClienteActionPerformed

    private void btCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadUsuariosActionPerformed
        new CadUsuario().setVisible(true);//que quer abrir
    }//GEN-LAST:event_btCadUsuariosActionPerformed

    private void btCadOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadOSActionPerformed
        new CadChamado().setVisible(true);
    }//GEN-LAST:event_btCadOSActionPerformed

    private void btCadAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadAtendimentosActionPerformed
        new ListaChamados().setVisible(true);
    }//GEN-LAST:event_btCadAtendimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenu MenuChamados;
    private javax.swing.JButton btCadAtendimentos;
    private javax.swing.JButton btCadCliente;
    private javax.swing.JButton btCadOS;
    private javax.swing.JButton btCadUsuarios;
    private javax.swing.JMenuItem imAtendimentos;
    private javax.swing.JMenuItem imChamados;
    private javax.swing.JMenuItem imClientes;
    private javax.swing.JMenuItem imSair;
    private javax.swing.JMenuItem imSobre;
    private javax.swing.JMenuItem imUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JPanel pnCadAtendimentos;
    private javax.swing.JPanel pnCadClientes;
    private javax.swing.JPanel pnCadOS;
    private javax.swing.JPanel pnCadUsers;
    // End of variables declaration//GEN-END:variables
}
